### PR TITLE
Support multiple configs with loader

### PR DESCRIPTION
**Pull request by akshayp**
This adds support to the plugin so that the loader is able to generate multiple acss files instead of a single config. Our use case here is the ability to generate specific bundles of css for each theme. I've also upgraded the project to support webpack 2.x

### CODE REVIEW

**Comment by tom76kimo** [comment]
Looks good to me, just is there something wrong with jenkins-mocha?

**Comment by tom76kimo** [comment]
https://github.com/acss-io/webpack-atomizer-loader/pull/11

I removed `jenkins-mocha`. Please pull latest code and the build should pass.

**Comment by akshayp** [comment]
Thanks @tom76kimo looks like this should be good to go 👍

**Comment by tom76kimo** [comment]
Published npm module with this feature as version `0.2.1`

**Comment by akshayp** [comment]
thanks for the quick turn around @tom76kimo!

**Pull request merged**
