### PR TITLE
fix: support multiple sources by storing the parsed class names globally

### PR DESCRIPTION
**Pull request by dword-design**
This PR offers an alternative solution to https://github.com/acss-io/webpack-atomizer-loader/pull/51 by storing the parsed class names globally. It also adds `stealthy-require` to the tests because otherwise the parsed class names will be available to all tests, which shouldn't be the case. This makes sure that each test has its very own loader and parsed data.

### CODE REVIEW

**Review by redonkulus — APPROVED** [review]
LGTM

**Comment by redonkulus** [comment]
Will this have an unintended side effects for applications that were expecting the previous behavior to remain?

**Comment by TonyBogdanov** [comment]
@redonkulus I'm no expert, but I think the *gather-all-classes-for-the-current-webpack-build-from-all-sources* was always the expected behavior, not the other way around.

**Review by redonkulus — APPROVED** [review]

**Comment by redonkulus** [comment]
Release in https://github.com/acss-io/webpack-atomizer-loader/releases/tag/v1.3.1

@dword-design FYI the new test seems to sometimes timeout locally for me, if you run it a few times in a row. Are you able to reproduce this?

**Comment by dword-design** [comment]
@redonkulus Sry for the late reply. I thought about the side effects thing again and I'd second @TonyBogdanov that the global gathering way is the intended.

**Pull request merged**
