### PR TITLE
Updated README to reflect new name and updated Atomizer depdency

### PR DESCRIPTION
**Pull request by soluml**

### CODE REVIEW

**Comment by tom76kimo** [comment]
:+1:

**Comment by soluml** [comment]
@tom76kimo thanks for the quick merge! If you could push this up to NPM that'd be great!  Needing some of the new things in Atomizer 3.3.8 and we really love your loader 👍

**Comment by tom76kimo** [comment]
Sure, I will publish it in an hour.

**Comment by tom76kimo** [comment]
Published.

**Comment by soluml** [comment]
thanks 👍

**Pull request merged**
